version: "3.8"

services:
    nginx:
        build:
            context: dockerfiles
            dockerfile: nginx.Dockerfile
        ports:
            - "8080:80"
        #    - "443:443"
        volumes:
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./src:/var/www/html
        depends_on:
            - php
            - mysql
        restart: always
        environment:
            TZ: "Europe/Moscow"

    php:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}-php
        ports:
            - "9000:9000"
        volumes:
            - ./src:/var/www/html
        restart: always
        environment:
            TZ: "Europe/Moscow"
            BITRIX_VA_VER: 7.5.0
            PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d/common/:/usr/local/etc/php/conf.d/:/usr/local/etc/php/conf.d/site/

    mysql:
        build:
            context: dockerfiles
            dockerfile: mysql.Dockerfile
        ports:
            - "3316:3306"
        env_file:
            - env/mysql.env
        volumes:
            - db_data:/var/lib/mysql
            - ./config/mysql:/etc/mysql/config
        restart: always

    mailhog:
        image: mailhog/mailhog
        restart: unless-stopped
        ports:
            - "8025:8025" # web ui
            - "1025:1025" # SMTP server

    memcached:
        build:
            context: dockerfiles
            dockerfile: memcashed.Dockerfile
        restart: always
        environment:
            TZ: "Europe/Moscow"

    sphinx:
        build:
            context: dockerfiles
            dockerfile: sphinx.Dockerfile
        restart: always
        ports:
            -   "9306:9306"
        volumes:
            - ./config/sphinx/sphinx.conf/etc/sphinxsearch/sphinx.conf
            - sphinx_data:/var/lib/sphinx/data
            - ./config/sphinx:/app/conf
            - ./data/sphinx/run:/app/run
            - ./data/sphinx/index:/app/index
            - ./data/sphinx/dicts:/app/dicts
            - ./data/sphinx/synonyms:/app/synonyms
            - ./logs/sphinx:/app/logs
        depends_on:
            - mysql
        environment:
            TZ: "Europe/Moscow"

volumes:
    db_data:
    sphinx_data:

networks:
    bitrix:
        driver: bridge

