version: "3.8"

services:
    nginx:
        build:
            context: dockerfiles
            dockerfile: nginx.Dockerfile
        ports:
            - "8080:80"
        #    - "443:443"
        volumes:
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./src:/var/www/html
        depends_on:
            - php
            - mysql
        restart: always
        environment:
            TZ: "Europe/Moscow"

    php:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}-php
        ports:
            - "9000:9000"
        volumes:
            - ./src:/var/www/html
        restart: always
        environment:
            TZ: "Europe/Moscow"
            BITRIX_VA_VER: 7.5.0
            PHP_INI_SCAN_DIR: /usr/local/etc/php/conf.d/common/:/usr/local/etc/php/conf.d/:/usr/local/etc/php/conf.d/site/

    mysql:
        build:
            context: dockerfiles
            dockerfile: mysql.Dockerfile
        ports:
            - "3316:3306"
        environment:
            MYSQL_DATABASE: projectdb
            MYSQL_USER: projectmysqluser
            MYSQL_PASSWORD: mysqlpwdproject
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
            - ./config/mysql:/etc/mysql/config
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8091:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: projectdb
            MYSQL_USER: projectmysqluser
            MYSQL_PASSWORD: mysqlpwdproject
            TZ: "Europe/Moscow"
        depends_on:
            - mysql

    mailhog:
        image: mailhog/mailhog
        restart: unless-stopped
        ports:
            - "8025:8025" # web ui
            - "1025:1025" # SMTP server

    memcached:
        build:
            context: dockerfiles
            dockerfile: memcashed.Dockerfile
        restart: always
        environment:
            TZ: "Europe/Moscow"

    sphinx:
        image: registry.gitlab.com/bitrix-docker/images/sphinx:latest
        restart: always
        depends_on:
            - mysql
        environment:
            TZ: "Europe/Moscow"

volumes:
    db_data:

networks:
    bitrix:
        driver: bridge

